version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html/:/usr/share/nginx/html/
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on: 
      - php-fpm

  php-fpm:
    image: php:7.4-fpm
    container_name: php-fpm
    volumes:
      - ./html/:/usr/share/nginx/html/
    ports:
      - "9000:9000"

  filebeat:
    image: elastic/filebeat:7.16.2
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/var/log/nginx
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock